sudo: false
dist: trusty

notifications:
  email: false

language: c

matrix:
  include:
    - os: linux
      compiler: clang-4.0
      env: C_COMPILER="clang-4.0"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:jonathonf/curl'
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main"
              key_url:    "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - clang-4.0
            - curl
    - os: linux
      compiler: gcc-5
      env: C_COMPILER="gcc-5"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:jonathonf/curl'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - curl
    - os: linux
      compiler: gcc-6
      env: C_COMPILER="gcc-6"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:jonathonf/curl'
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - curl
            
script:
  - export CC="$C_COMPILER"